//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teste_fiap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public int Codigo { get; set; }
        public int CodigoSegmento { get; set; }
        public int CodigoCurso { get; set; }
        public int RM { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string DDD { get; set; }
        public string Telefone { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Segmento Segmento { get; set; }
    }
}
